[workspace]
members=["warhorse_client", "warhorse_cpp", "warhorse_protocol", "warhorse_server", "warhorse_ui", "warhorse_ui_experiments"]
resolver = "2"

[workspace.dependencies]
serde = "1.0.134"
serde_json = "1.0.134"
tokio = "1.42.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
