[package]
name = "warhorse_ui_experiments"
version = "0.1.0"
edition = "2021"

[dependencies]
warhorse_ui = { path = "../warhorse_ui" }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8.1"
bevy = { version = "0.15.0" }

[build-dependencies]
warhorse_ui = { path = "../warhorse_ui" }
